name: Freestyle A/V
favicon: null
layout_spectrum: 1
typography_spectrum: 0.59027
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#181818'
    - '#695e4a'
    - '#ab2433'
    - '#76a89d'
  brandStrength: 0.5
  lightness: 0.8846362601034343
  saturation: 0.75
  rhythmicContrast: 0.6809518663212657
purpose: []
